### ISSUE TITLE
achieve successful `vpm compat` on airs-bp3

### ISSUE THREAD

**Issue by host6** [voedger/voedger#1146]
## Problem

**Now, in current architecture**
`vpm compat` is expected to work 

- Problem (hot): `vpm compat -C <full-path-to-airs-bp3 apps/untill/airsbp> ` ->
```
panic: unexpected root table kind 0

goroutine 8 [running]:
github.com/voedger/voedger/pkg/parser.getNestedTableKind(0x20?)
	c:/workspace/go/voedger/pkg/parser/utils.go:270 +0xaa
github.com/voedger/voedger/pkg/parser.analyseNestedTables({0xc00047b7c0, 0x5, 0xc000359760?}, 0xe0?, 0xc0002f13e0)
	c:/workspace/go/voedger/pkg/parser/impl_analyse.go:582 +0x37a
github.com/voedger/voedger/pkg/parser.analyseTable(0xc000359760, 0xc0002f13e0)
	c:/workspace/go/voedger/pkg/parser/impl_analyse.go:483 +0x65
github.com/voedger/voedger/pkg/parser.analyse.func1({0x980f60?, 0xc000359760?}, 0xc0003580b0?)
	c:/workspace/go/voedger/pkg/parser/impl_analyse.go:54 +0x197
github.com/voedger/voedger/pkg/parser.iterateContext.func1({0x980f60, 0xc000359760})
	c:/workspace/go/voedger/pkg/parser/utils.go:184 +0x36
github.com/voedger/voedger/pkg/parser.(*WorkspaceStmt).Iterate(0xc000358e70, 0xc0005e5848)
	c:/workspace/go/voedger/pkg/parser/types.go:216 +0x5d
github.com/voedger/voedger/pkg/parser.iterateContext(0xc0002f13e0, 0xa116d8)
	c:/workspace/go/voedger/pkg/parser/utils.go:183 +0x76
github.com/voedger/voedger/pkg/parser.iterateContext.func1({0x981860, 0xc000358e70})
	c:/workspace/go/voedger/pkg/parser/utils.go:192 +0xe5
github.com/voedger/voedger/pkg/parser.(*SchemaAST).Iterate(0xc000462000, 0xc0005e5830)
	c:/workspace/go/voedger/pkg/parser/types.go:82 +0x37
github.com/voedger/voedger/pkg/parser.iterateContext(0xc0002f13b0, 0xa116d8)
	c:/workspace/go/voedger/pkg/parser/utils.go:183 +0x76
github.com/voedger/voedger/pkg/parser.iteratePackage(...)
	c:/workspace/go/voedger/pkg/parser/utils.go:170
github.com/voedger/voedger/pkg/parser.analyse(0xc00075bac0, 0xc0003ca570)
	c:/workspace/go/voedger/pkg/parser/impl_analyse.go:45 +0x8e
github.com/voedger/voedger/pkg/parser.buildAppSchemaImpl({0xc0003b1e20, 0x4, 0xc000a076b0?})
	c:/workspace/go/voedger/pkg/parser/impl.go:293 +0x229
github.com/voedger/voedger/pkg/parser.BuildAppSchema(...)
	c:/workspace/go/voedger/pkg/parser/provide.go:56
github.com/voedger/voedger/cmd/vpm.appDefFromBaselineDir({0x9c8d3c, 0x3})
	c:/workspace/go/voedger/cmd/vpm/compat.go:169 +0x5e5
github.com/voedger/voedger/cmd/vpm.compat(0x3?, {{0x9dcfbd, 0x2b}, {0x9c8d3c, 0x3}, {0x0, 0x0}}, {0x0, 0x0, 0x0})
	c:/workspace/go/voedger/cmd/vpm/compat.go:54 +0x65
github.com/voedger/voedger/cmd/vpm.newCompatCmd.func1(0xc00018c400?, {0xc0002242d0?, 0x4?, 0x9c9124?})
	c:/workspace/go/voedger/cmd/vpm/compat.go:42 +0x1b2
github.com/spf13/cobra.(*Command).execute(0xc000004900, {0xc000224270, 0x3, 0x3})
	C:/workspace/go/gopath/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x87c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000004c00)
	C:/workspace/go/gopath/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	C:/workspace/go/gopath/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	C:/workspace/go/gopath/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:985
github.com/untillpro/goutils/cobrau.ExecCommandAndCatchInterrupt.func1({0xa7f7f0?, 0xc00005c9b0?})
	C:/workspace/go/gopath/pkg/mod/github.com/untillpro/goutils@v0.0.0-20231117130619-11fe1908c171/cobrau/catch_interrupt.go:21 +0x50
github.com/untillpro/goutils/cobrau.goAndCatchInterrupt.func1()
	C:/workspace/go/gopath/pkg/mod/github.com/untillpro/goutils@v0.0.0-20231117130619-11fe1908c171/cobrau/catch_interrupt.go:40 +0x6e
created by github.com/untillpro/goutils/cobrau.goAndCatchInterrupt in goroutine 6
	C:/workspace/go/gopath/pkg/mod/github.com/untillpro/goutils@v0.0.0-20231117130619-11fe1908c171/cobrau/catch_interrupt.go:38 +0x171

```

**Describe the solution you'd like**
investigate and fix

**Comment by host6** [comment]
Figured out. Need to demand that target dir should actually baseline dir. Will be fixed in #1158
