### ISSUE TITLE
nil memory dereference on update a record with uniques

### ISSUE THREAD

**Issue by host6** [voedger/voedger#1408]
**Describe the bug**
nil memory dereference 

**To Reproduce**
1. define a table without uniques
2. insert a record
3. define unique on the table 
4. update the existing record
5. nil memory dereference in uniques engine

**Expected behavior**
insert record, add unique, update the record -> do nothing to keep previous events work. New uniuqu will work starting from the next new record

**Comment by host6** [comment]
```
 serving  POST   /api/untill/airs-bp/140737488487035/c.sys.CUD
2024-02-06T15:32:00.710609625Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    | 02/06 15:32:00.710: ---: [vvm.ProvideCluster.provideIBus.func13:46]: request body:
2024-02-06T15:32:00.710615294Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    |  {"cuds":[{"sys.ID":322680000131140,"fields":{"LastPayoutTransferStatus":2}}]}
2024-02-06T15:32:01.648642325Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    | panic: runtime error: invalid memory address or nil pointer dereference
2024-02-06T15:32:01.648674914Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x90a2e6]
2024-02-06T15:32:01.648683243Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    |
2024-02-06T15:32:01.648689313Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    | goroutine 4252 [running]:
2024-02-06T15:32:01.648695513Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    | github.com/voedger/voedger/pkg/sys/uniques.update({0x7f7520ea5c78, 0xc00172f440}, {0xe49880, 0xc0036c05d8}, {0x7f7520ea5cd0, 0xc00172f440}, {0xc0009a4a40, 0x2, 0x2}, {{0xc00010cbee, ...}, ...})
2024-02-06T15:32:01.648699953Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    |      /home/runner/go/pkg/mod/github.com/voedger/voedger@v0.0.0-20240201091748-f9976cad60c8/pkg/sys/uniques/impl.go:77 +0x206
2024-02-06T15:32:01.648717873Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    | github.com/voedger/voedger/pkg/sys/uniques.handleCUD({0xe49880, 0xc0036c05d8}, {0x7f7520ea5c78, 0xc00172f440}, {0x7f7520ea5cd0, 0xc00172f440}, {0xc0009a4a40, 0x2, 0x2}, {{0xc00010cbee, ...}, ...})
2024-02-06T15:32:01.648736712Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    |      /home/runner/go/pkg/mod/github.com/voedger/voedger@v0.0.0-20240201091748-f9976cad60c8/pkg/sys/uniques/impl.go:48 +0x16b
2024-02-06T15:32:01.648741012Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    | github.com/voedger/voedger/pkg/sys/uniques.provideApplyUniques.func1.1({0xe49880, 0xc0036c05d8})
2024-02-06T15:32:01.648744952Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    |      /home/runner/go/pkg/mod/github.com/voedger/voedger@v0.0.0-20240201091748-f9976cad60c8/pkg/sys/uniques/impl.go:31 +0x1dc
2024-02-06T15:32:01.648749012Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    | github.com/voedger/voedger/pkg/sys/uniques.provideApplyUniques.func1.ForEachError[...].func2()
2024-02-06T15:32:01.648753112Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    |      /home/runner/go/pkg/mod/github.com/untillpro/goutils@v0.0.0-20231117130619-11fe1908c171/iterate/impl.go:39 +0x30
2024-02-06T15:32:01.648758072Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    | github.com/voedger/voedger/pkg/istructsmem.(*cudType).enumRecs(0xc0036c4bd8, 0xc003683cc0)
2024-02-06T15:32:01.648763501Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    |      /home/runner/go/pkg/mod/github.com/voedger/voedger@v0.0.0-20240201091748-f9976cad60c8/pkg/istructsmem/event-types.go:428 +0xec
2024-02-06T15:32:01.648769391Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    | github.com/voedger/voedger/pkg/istructsmem.(*eventType).CUDs(0xbb8280?, 0xc000734c01?)
2024-02-06T15:32:01.648776751Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    |      /home/runner/go/pkg/mod/github.com/voedger/voedger@v0.0.0-20240201091748-f9976cad60c8/pkg/istructsmem/event-types.go:267 +0x1b
2024-02-06T15:32:01.648783331Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    | github.com/untillpro/goutils/iterate.ForEachError[...](...)
2024-02-06T15:32:01.648788791Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    |      /home/runner/go/pkg/mod/github.com/untillpro/goutils@v0.0.0-20231117130619-11fe1908c171/iterate/impl.go:35
2024-02-06T15:32:01.648794491Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    | github.com/voedger/voedger/pkg/sys/uniques.provideApplyUniques.func1({0xe46b58?, 0xc0036c4a00?}, {0x7f7520ea5c78?, 0xc00172f440}, {0x7f7520ea5cd0?, 0xc00172f440})
2024-02-06T15:32:01.648799990Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    |      /home/runner/go/pkg/mod/github.com/voedger/voedger@v0.0.0-20240201091748-f9976cad60c8/pkg/sys/uniques/impl.go:25 +0x199
2024-02-06T15:32:01.648805290Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    | github.com/voedger/voedger/pkg/projectors.newSyncBranch.func1({0x40c8cc?, 0xb5d8c0?}, {0xb4f9c0?, 0x0?})
2024-02-06T15:32:01.648810540Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    |      /home/runner/go/pkg/mod/github.com/voedger/voedger@v0.0.0-20240201091748-f9976cad60c8/pkg/projectors/impl.go:81 +0x114
2024-02-06T15:32:01.648819790Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    | github.com/voedger/voedger/pkg/pipeline.(*implISyncOperatorSimple).DoSync(0x1?, {0xe42630?, 0xc000173770?}, {0xbc7a80?, 0xc0017d0d80?})
2024-02-06T15:32:01.648827130Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    |      /home/runner/go/pkg/mod/github.com/voedger/voedger@v0.0.0-20240201091748-f9976cad60c8/pkg/pipeline/noop-impl.go:59 +0x3c
2024-02-06T15:32:01.648832930Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    | github.com/voedger/voedger/pkg/pipeline.(*WiredOperator).doSync(0xc0012b12d0, {0xbc7a80?, 0xc0017d0d80?}, {0xbc7a80, 0xc0017d0d80})
2024-02-06T15:32:01.648838580Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    |      /home/runner/go/pkg/mod/github.com/voedger/voedger@v0.0.0-20240201091748-f9976cad60c8/pkg/pipeline/wired-operator.go:102 +0x85
2024-02-06T15:32:01.648844259Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    | github.com/voedger/voedger/pkg/pipeline.processSyncOp(0xc0012b12d0, {0xbc7a80, 0xc0017d0d80})
2024-02-06T15:32:01.648849829Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    |      /home/runner/go/pkg/mod/github.com/voedger/voedger@v0.0.0-20240201091748-f9976cad60c8/pkg/pipeline/sync-pipeline-impl.go:78 +0x36d
2024-02-06T15:32:01.648862489Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    | github.com/voedger/voedger/pkg/pipeline.(*SyncPipeline).SendSync(0xc001706640, {0xbc7a80, 0xc0017d0d80})
2024-02-06T15:32:01.648871389Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    |      /home/runner/go/pkg/mod/github.com/voedger/voedger@v0.0.0-20240201091748-f9976cad60c8/pkg/pipeline/sync-pipeline-impl.go:55 +0x8f
2024-02-06T15:32:01.648879088Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    | github.com/voedger/voedger/pkg/pipeline.(*SyncPipeline).DoSync(0xc6de72?, {0x9?, 0xe3d608?}, {0xbc7a80?, 0xc0017d0d80?})
2024-02-06T15:32:01.648885728Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    |      /home/runner/go/pkg/mod/github.com/voedger/voedger@v0.0.0-20240201091748-f9976cad60c8/pkg/pipeline/sync-pipeline-impl.go:47 +0x25
2024-02-06T15:32:01.648891548Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    | github.com/voedger/voedger/pkg/pipeline.forkOperator.DoSync.func1(0xc00141bfd0?, {0x7f7520479090?, 0xc001706640?})
2024-02-06T15:32:01.648897268Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    |      /home/runner/go/pkg/mod/github.com/voedger/voedger@v0.0.0-20240201091748-f9976cad60c8/pkg/pipeline/fork-operator-impl.go:43 +0x8f
2024-02-06T15:32:01.648904098Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    | created by github.com/voedger/voedger/pkg/pipeline.forkOperator.DoSync in goroutine 4242
2024-02-06T15:32:01.648909868Z rc5_airs-bp3.1.1s1m6p61cx1y@app-node-1    |      /home/runner/go/pkg/mod/github.com/voedger/voedger@v0.0.0-20240201091748-f9976cad60c8/pkg/pipeline/fork-operator-impl.go:41 +0x14b
```
