### ISSUE TITLE
parser: nil memory dereference on compile sys.sql

### ISSUE THREAD

**Issue by host6** [voedger/voedger#1801]
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x111d18d]

goroutine 19 [running]:
testing.tRunner.func1.2({0x1303400, 0x1975330})
	C:/Program Files/Go/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
	C:/Program Files/Go/src/testing/testing.go:1634 +0x377
panic({0x1303400?, 0x1975330?})
	C:/Program Files/Go/src/runtime/panic.go:770 +0x132
github.com/voedger/voedger/pkg/parser.includeFromInheritedWorkspaces.func1(0xc0005460c0, 0xc00039d128)
	c:/Workspace/voedger/pkg/parser/impl_analyse.go:915 +0x66d
github.com/voedger/voedger/pkg/parser.includeFromInheritedWorkspaces(0xc0005460c0, 0xc0003430b0)
	c:/Workspace/voedger/pkg/parser/impl_analyse.go:918 +0x21f
github.com/voedger/voedger/pkg/parser.analyse.func4({0x135d9c0?, 0xc0005460c0?}, 0x18?)
	c:/Workspace/voedger/pkg/parser/impl_analyse.go:119 +0x30
github.com/voedger/voedger/pkg/parser.iterateContext.func1({0x135d9c0, 0xc0005460c0})
	c:/Workspace/voedger/pkg/parser/utils.go:234 +0x33
github.com/voedger/voedger/pkg/parser.(*SchemaAST).Iterate(0xc000343f50, 0xc00039d6e0)
	c:/Workspace/voedger/pkg/parser/types.go:94 +0x37
github.com/voedger/voedger/pkg/parser.iterateContext(0xc0003430b0, 0x141b0b8)
	c:/Workspace/voedger/pkg/parser/utils.go:233 +0x76
github.com/voedger/voedger/pkg/parser.analyse(0xc0002157c0, {0xc00039cac8, 0x3, 0x8?})
	c:/Workspace/voedger/pkg/parser/impl_analyse.go:117 +0x25b
github.com/voedger/voedger/pkg/parser.buildAppSchemaImpl({0xc00039cac8, 0x3, 0x3})
	c:/Workspace/voedger/pkg/parser/impl.go:331 +0x40f
github.com/voedger/voedger/pkg/parser.BuildAppSchema(...)
	c:/Workspace/voedger/pkg/parser/provide.go:56
github.com/voedger/voedger/pkg/compile.compile({0x14c3af8, 0x1})
	c:/Workspace/voedger/pkg/compile/impl.go:63 +0xa4e
github.com/voedger/voedger/pkg/compile.Compile(...)
	c:/Workspace/voedger/pkg/compile/provide.go:10
github.com/voedger/voedger/cmd/vpm.TestSysSQLCompile(0xc0000f9ba0)
	c:/Workspace/voedger/cmd/vpm/main_test.go:253 +0x25
testing.tRunner(0xc0000f9ba0, 0x141a4d0)
	C:/Program Files/Go/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 1
	C:/Program Files/Go/src/testing/testing.go:1742 +0x390
FAIL	github.com/voedger/voedger/cmd/vpm	1.305s
```
Steps to reproduce:
- write a test at any place of voedger where there are no .sql files:
```golang
func TestSysSQLCompile(t *testing.T) {
	_, err := compile.Compile(".")
	require.NoError(t, err)
}
```
- copy [sys.sql](https://github.com/voedger/voedger/blob/main/pkg/sys/sys.sql) near the file with the test
- run the test

**Comment by michael-say** [comment]
@host6 did that in "compile" package, works as expected:
```
Received unexpected error:
        	            	sys.sql:4:1: undefined table kind
        	            	sys.sql:6:1: undefined table kind
```
did you merge all the updates from main?
