### ISSUE TITLE
Result storage: cannot be used in tests with Assert(...)

### ISSUE THREAD

**Issue by michael-say** [voedger/voedger#2181]
```go
	test.RequireIntent(t, state.Result, appdef.NullFullQName, func(_ istructs.IStateKeyBuilder) {}).Assert(func(require *require.Assertions, value istructs.IStateValue) {
		require.Equal(int32(42), value.AsInt32("ReadValue"))
	})
```

produces error:
```
--- FAIL: Test_CommandStorages (0.01s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x114b61e]

goroutine 19 [running]:
testing.tRunner.func1.2({0x1208ce0, 0x16057b0})
	C:/Users/michael/sdk/go1.21.5/src/testing/testing.go:1545 +0x238
testing.tRunner.func1()
	C:/Users/michael/sdk/go1.21.5/src/testing/testing.go:1548 +0x397
panic({0x1208ce0?, 0x16057b0?})
	C:/Users/michael/sdk/go1.21.5/src/runtime/panic.go:914 +0x21f
github.com/voedger/voedger/pkg/state.(*resultValueBuilder).BuildValue(0x0?)
	<autogenerated>:1 +0x1e
```

**Comment by michael-say** [comment]
fixed in previous commits
