### ISSUE TITLE
nil pointer dereference on sidecar app command call

### ISSUE THREAD

**Issue by host6** [voedger/voedger#2527]
query call from a sidecar app works well but command call is failed:

```
=== RUN   TestSidecarApps_BasicUsage/command
08/22 17:27:17.814: *****: [vvm.ProvideCluster.ProvideServiceFactory.func7.1.4:159]: runtime error: invalid memory address or nil pointer dereference (recovered by wazero)
wasm stack trace:
	env.hostGetValue(i64) i64
	.TestCmdEcho()

Go runtime stack trace:
goroutine 114 [running]:
runtime/debug.Stack()
	C:/Program Files/Go/src/runtime/debug/stack.go:24 +0x5e
github.com/tetratelabs/wazero/internal/wasmdebug.(*stackTrace).FromRecovered(0x0?, {0xa07080, 0x1385d30})
	C:/workspace/go/gopath/pkg/mod/github.com/tetratelabs/wazero@v1.7.2/internal/wasmdebug/debug.go:142 +0x15c
github.com/tetratelabs/wazero/internal/engine/interpreter.(*callEngine).recoverOnCall(0xc0035c8000, {0xca4e80, 0xc0002462d0}, 0xc00354c300, {0xa07080, 0x1385d30})
	C:/workspace/go/gopath/pkg/mod/github.com/tetratelabs/wazero@v1.7.2/internal/engine/interpreter/interpreter.go:647 +0x388
github.com/tetratelabs/wazero/internal/engine/interpreter.(*callEngine).call.func1()
	C:/workspace/go/gopath/pkg/mod/github.com/tetratelabs/wazero@v1.7.2/internal/engine/interpreter/interpreter.go:582 +0xa5
panic({0xa07080?, 0x1385d30?})
	C:/Program Files/Go/src/runtime/panic.go:770 +0x132
github.com/voedger/voedger/pkg/sys/storages.(*commandContextStorage).Get(0xc000262080, {0xc0004f00f0?, 0xc0035c58f8?})
	c:/workspace/go/voedger/pkg/sys/storages/impl_commandcontext_storage.go:48 +0x1a
github.com/voedger/voedger/pkg/state/stateprovide.(*hostState).CanExist(0xc0001fe000, {0xcb1178, 0xc002c61410})
	c:/workspace/go/voedger/pkg/state/stateprovide/impl_host_state.go:116 +0x2d0
github.com/voedger/voedger/pkg/state/stateprovide.(*hostState).MustExist(0xc0001fe000, {0xcb1178, 0xc002c61410})
	c:/workspace/go/voedger/pkg/state/stateprovide/impl_host_state.go:165 +0x2c
github.com/voedger/voedger/pkg/state/safestate.(*safeState).MustGetValue(0xc002c65030, 0xc00264b580?)
	c:/workspace/go/voedger/pkg/state/safestate/impl.go:57 +0x4f
github.com/voedger/voedger/pkg/iextengine/wazero.(*wazeroExtEngine).hostMustExist(...)
	c:/workspace/go/voedger/pkg/iextengine/wazero/impl.go:474
reflect.Value.call({0x9ce540?, 0xc002d66c90?, 0xc0035c6138?}, {0xb35a43, 0x4}, {0xc002c1c900, 0x1, 0xc0035c6168?})
	C:/Program Files/Go/src/reflect/value.go:596 +0xca6
reflect.Value.Call({0x9ce540?, 0xc002d66c90?, 0xc002c1c8e8?}, {0xc002c1c900?, 0xa1b840?, 0xc0023161d0?})
	C:/Program Files/Go/src/reflect/value.go:380 +0xb9
github.com/tetratelabs/wazero/internal/wasm.callGoFunc({0x0, 0x0}, {0x0, 0x0}, 0xc00321ec30, {0xc003592528, 0x1, 0x1397bc0?})
	C:/workspace/go/gopath/pkg/mod/github.com/tetratelabs/wazero@v1.7.2/internal/wasm/gofunc.go:126 +0x3d8
github.com/tetratelabs/wazero/internal/wasm.(*reflectGoFunction).Call(0xc00032a648?, {0xca4e80?, 0xc0002462d0?}, {0xc003592528?, 0x9acf20?, 0xc00032bf80?})
	C:/workspace/go/gopath/pkg/mod/github.com/tetratelabs/wazero@v1.7.2/internal/wasm/gofunc.go:79 +0x55
github.com/tetratelabs/wazero/internal/engine/interpreter.(*callEngine).callGoFunc(0xc0035c8000, {0xca4e80, 0xc0002462d0}, 0xc00354c300, 0xc0035be088, {0xc003592528, 0x1, 0xb})
	C:/workspace/go/gopath/pkg/mod/github.com/tetratelabs/wazero@v1.7.2/internal/engine/interpreter/interpreter.go:684 +0x498
github.com/tetratelabs/wazero/internal/engine/interpreter.(*callEngine).callGoFuncWithStack(0xc0035c8000, {0xca4e80?, 0xc0002462d0?}, 0xca4da0?, 0x14676a0?)
	C:/workspace/go/gopath/pkg/mod/github.com/tetratelabs/wazero@v1.7.2/internal/engine/interpreter/interpreter.go:4577 +0xa5
github.com/tetratelabs/wazero/internal/engine/interpreter.(*callEngine).callFunction(0x80?, {0xca4e80?, 0xc0002462d0?}, 0xc002c1c8a0?, 0x0?)
	C:/workspace/go/gopath/pkg/mod/github.com/tetratelabs/wazero@v1.7.2/internal/engine/interpreter/interpreter.go:659 +0x45
github.com/tetratelabs/wazero/internal/engine/interpreter.(*callEngine).callNativeFunc.func1({0xca4e80, 0xc0002462d0}, 0xc0035c8000, 0xc0035c7368, 0xc0035c73d0, 0xc0035c71e0, 0xc0035be448, {0xc0035be008, 0x23, 0x23}, ...)
	C:/workspace/go/gopath/pkg/mod/github.com/tetratelabs/wazero@v1.7.2/internal/engine/interpreter/interpreter.go:755 +0x138
github.com/tetratelabs/wazero/internal/engine/interpreter.(*callEngine).callNativeFunc(0xc0035c8000, {0xca4e80, 0xc0002462d0}, 0xc00354c300, 0xc0035be448)
	C:/workspace/go/gopath/pkg/mod/github.com/tetratelabs/wazero@v1.7.2/internal/engine/interpreter/interpreter.go:756 +0x5b3
github.com/tetratelabs/wazero/internal/engine/interpreter.(*callEngine).callFunction(0xc00354c300?, {0xca4e80?, 0xc0002462d0?}, 0x137f9d?, 0x1f0ce4800a0?)
	C:/workspace/go/gopath/pkg/mod/github.com/tetratelabs/wazero@v1.7.2/internal/engine/interpreter/interpreter.go:663 +0x3c
github.com/tetratelabs/wazero/internal/engine/interpreter.(*callEngine).call(0xc0035c8000, {0xca4e80, 0xc0002462d0}, {0x0, 0x0, 0x8a8ee8?}, {0x0, 0x0, 0x0})
	C:/workspace/go/gopath/pkg/mod/github.com/tetratelabs/wazero@v1.7.2/internal/engine/interpreter/interpreter.go:593 +0x2d2
github.com/tetratelabs/wazero/internal/engine/interpreter.(*callEngine).Call(0x1f0ce483458?, {0xca4e80?, 0xc0002462d0?}, {0x0?, 0x0?, 0x2a?})
	C:/workspace/go/gopath/pkg/mod/github.com/tetratelabs/wazero@v1.7.2/internal/engine/interpreter/interpreter.go:544 +0xc6
github.com/voedger/voedger/pkg/iextengine/wazero.(*wazeroExtEngine).invoke(0xc0000103c0, {0xca4e80, 0xc0002462d0}, {{0xc00025c600?, 0xc002317710?}, {0xc000032856?, 0x0?}}, {0xcb2628, 0xc002c61320})
	c:/workspace/go/voedger/pkg/iextengine/wazero/impl.go:416 +0x326
github.com/voedger/voedger/pkg/iextengine/wazero.(*wazeroExtEngine).Invoke(0xc0000103c0, {0xca4e80, 0xc0002462d0}, {{0xc00025c600?, 0x6?}, {0xc000032856?, 0x0?}}, {0xcb2628, 0xc002c61320})
	c:/workspace/go/voedger/pkg/iextengine/wazero/impl.go:434 +0x71
github.com/voedger/voedger/pkg/appparts.(*borrowedPartition).Invoke(0xc002114680, {0xca4e80, 0xc0002462d0}, {{0xc000032847?, 0xc0004c6780?}, {0xc000032856?, 0x0?}}, {0x1f0ce1e4a30, 0xc0002c00b0}, {0x1f0ce1e4ab8, ...})
	c:/workspace/go/voedger/pkg/appparts/impl_app.go:235 +0x3c5
github.com/voedger/voedger/pkg/processors/command.execCommand({0xca4e80, 0xc0002462d0}, {0xc9dd80?, 0xc002c62a08})
	c:/workspace/go/voedger/pkg/processors/command/impl.go:473 +0xef
github.com/voedger/voedger/pkg/pipeline.(*implISyncOperatorSimple).DoSync(0x1390570?, {0xca4e80?, 0xc0002462d0?}, {0xc9dd80?, 0xc002c62a08?})
	c:/workspace/go/voedger/pkg/pipeline/noop-impl.go:59 +0x3c
github.com/voedger/voedger/pkg/pipeline.(*WiredOperator).doSync(0xc0001ff110, {0xc0023179f8?, 0xc0035bcd10?}, {0xc9dd80, 0xc002c62a08})
	c:/workspace/go/voedger/pkg/pipeline/wired-operator.go:102 +0xe2
github.com/voedger/voedger/pkg/pipeline.processSyncOp(0xc0001ff110, {0xc9dd80, 0xc002c62a08})
	c:/workspace/go/voedger/pkg/pipeline/sync-pipeline-impl.go:78 +0xed
github.com/voedger/voedger/pkg/pipeline.(*SyncPipeline).SendSync(0xc00007e730, {0xc9dd80, 0xc002c62a08})
	c:/workspace/go/voedger/pkg/pipeline/sync-pipeline-impl.go:55 +0x8f
github.com/voedger/voedger/pkg/vvm.ProvideCluster.ProvideServiceFactory.func7.1.4(0xc002c62a08, {0xca2b40, 0xc00007e730}, 0xc0012540c0)
	c:/workspace/go/voedger/pkg/processors/command/provide.go:157 +0xbc
github.com/voedger/voedger/pkg/vvm.ProvideCluster.ProvideServiceFactory.func7.1({0xca4e80, 0xc0002462d0})
	c:/workspace/go/voedger/pkg/processors/command/provide.go:166 +0xd4e
github.com/voedger/voedger/pkg/pipeline.(*implIServiceSimple).Run(0x0?, {0xca4e80?, 0xc0002462d0?})
	c:/workspace/go/voedger/pkg/pipeline/noop-impl.go:73 +0x30
github.com/voedger/voedger/pkg/pipeline.(*serviceOperator).DoSync.func1()
	c:/workspace/go/voedger/pkg/pipeline/service-operator-impl.go:39 +0x85
created by github.com/voedger/voedger/pkg/pipeline.(*serviceOperator).DoSync in goroutine 58
	c:/workspace/go/voedger/pkg/pipeline/service-operator-impl.go:33 +0x179
```

**Comment by michael-say** [comment]
@host6 the problem happens because of [this](https://github.com/host6/voedger/blob/312df7e3d66a2f75930f5fdbe5db4d64f9d4c032/pkg/processors/command/types.go#L132)
